name: pipeline

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        pymc-version: ["without", "'pymc>=5.0.0'"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -e .
        pip install -r requirements-dev.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --statistics
    - name: Test without PyMC
      if: matrix.pymc-version == 'without'
      run: |
        pytest --cov=./murefi --cov-append --cov-report xml --cov-report term-missing murefi/tests.py
    - name: Install and test with PyMC
      if: matrix.pymc-version != 'without'
      run: |
        pip install ${{ matrix.pymc-version }}
        pytest --cov=./murefi --cov-append --cov-report xml --cov-report term-missing murefi/tests.py
    - name: Install and test with sunode
      if: matrix.pymc-version != 'without'
      run : |
        conda install -c conda-forge "sunode>=0.5.0"
        pytest --cov=./murefi --cov-append --cov-report xml --cov-report term-missing murefi/tests.py
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      if: matrix.python-version == 3.8
      with:
        file: ./coverage.xml
    - name: Test Wheel install and import
      run: |
        python setup.py bdist_wheel
        cd dist
        pip install murefi*.whl
        python -c "import murefi; print(murefi.__version__)"
