name: release-pipeline

on:
  release:
    types:
      - created


jobs:
  release-job:
    runs-on: ubuntu-latest
    env:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment-dev.yml
        create-args: >-
          python=3.11
    - name: Install dependencies
      run: |
        conda activate murefi-env
        pip install -e .
    - name: Test without PyMC
      run: |
        pytest --cov=./murefi --cov-append --cov-report xml --cov-report term-missing murefi/tests.py
    - name: Build package
      run: |
        python setup.py sdist bdist_wheel
    - name: Check version number match
      run: |
        echo "GITHUB_REF: ${GITHUB_REF}"
        # Make sure the package version is the same as the tag
        grep -Rq "^Version: ${GITHUB_REF:11}$" murefi.egg-info/PKG-INFO
    - name: Publish to PyPI
      run: |
        twine check dist/*
        twine upload --repository pypi --username __token__ --password ${PYPI_TOKEN} dist/*
    - name: Test installation
      run: |
        sleep 120
        pip install murefi==${GITHUB_REF:11}
